<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Automation Test"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="28.545">
  <properties />
            <testcase name="verifyUserShouldAddProductToTheCartSuccessfully" time="10.138" classname="com.automation.testsuite.WomenCategoryPageTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Product successfully added to your shopping cart] but found []"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Product successfully added to your shopping cart] but found []
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
  com.automation.testsuite.WomenCategoryPageTest.verifyUserShouldAddProductToTheCartSuccessfully(WomenCategoryPageTest.java:52)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyUserShouldAddProductToTheCartSuccessfully" time="5.712" classname="com.automation.testsuite.WomenCategoryPageTest" />
                <testcase name="verifyUserShouldAddProductToTheCartSuccessfully" time="6.925" classname="com.automation.testsuite.WomenCategoryPageTest" />
                <testcase name="verifyUserShouldAddProductToTheCartSuccessfully" time="5.770" classname="com.automation.testsuite.WomenCategoryPageTest" />
      
</testsuite>
